import { resolveEntryCoordinates } from "../../developer/sprite-mapping/atlasMapping";
import type { SpriteMappingState } from "../../developer/sprite-mapping/spriteMappingState";
import { renderVisualTemplateSelector } from "../visualTemplateSelector";
import { renderButton } from "../components/button";

function renderStateMetadata(state: string | null, direction: string | null): string {
  return `State: ${state ?? "default"} • Direction: ${direction ?? "none"}`;
}

export function renderSpriteMappingPanel(state: SpriteMappingState, activeTemplateId = "default-template"): string {
  const selected = state.document?.entries.find((entry) => entry.entryId === state.selectedEntryId) ?? state.document?.entries[0] ?? null;
  const selectedCoordinates = selected && state.document ? resolveEntryCoordinates(selected, state.changes) : null;
  const invalid = new Set(state.issues.filter((issue) => issue.entryId).map((issue) => issue.entryId));
  const dirty = Object.keys(state.changes.entryOverrides).length > 0 || state.changes.bulkOffset.x !== 0 || state.changes.bulkOffset.y !== 0;
  const canSave = Boolean(state.document) && dirty && invalid.size === 0 && !state.isSaving;
  const viewControls = `<div class="sprite-mapping-view-controls">${renderButton({ children: "−", id: "sprite-mapping-zoom-out", testId: "sprite-mapping-zoom-out", ariaLabel: "Zoom out", variant: "icon", disabled: state.zoom <= .5 })}<output data-testid="sprite-mapping-zoom-value">${Math.round(state.zoom * 100)}%</output>${renderButton({ children: "+", id: "sprite-mapping-zoom-in", testId: "sprite-mapping-zoom-in", ariaLabel: "Zoom in", variant: "icon", disabled: state.zoom >= 4 })}${renderButton({ children: "Reset view", id: "sprite-mapping-reset-view", testId: "sprite-mapping-reset-view", variant: "secondary", disabled: state.zoom === 1 && !state.viewPan.x && !state.viewPan.y })}</div>`;
  const actions = `${renderButton({ children: "Discard changes", id: "sprite-mapping-reset", testId: "sprite-mapping-reset", variant: "secondary", disabled: !dirty })}${renderButton({ children: state.isSaving ? "Saving…" : "Save coordinates", id: "sprite-mapping-save", testId: "sprite-mapping-save", busy: state.isSaving, disabled: !canSave })}${renderButton({ children: "Copy mapping JSON", id: "sprite-mapping-copy", testId: "sprite-mapping-copy", variant: "secondary", disabled: !state.document })}${renderButton({ children: "Download mapping JSON", id: "sprite-mapping-download", testId: "sprite-mapping-download", variant: "secondary", disabled: !state.document })}${renderButton({ children: "Return to Menu", id: "sprite-mapping-return", testId: "sprite-mapping-return", variant: "secondary" })}`;
  const selectedPanel = selected && selectedCoordinates ? `<section data-testid="sprite-mapping-selected"><strong>${selected.displayName}</strong><span>${selected.subjectKind} • ${renderStateMetadata(selected.state, selected.direction)}</span><label>X <input id="sprite-mapping-coordinate-x" data-testid="sprite-mapping-coordinate-x" type="number" step="1" value="${selectedCoordinates.x}"></label><label>Y <input id="sprite-mapping-coordinate-y" data-testid="sprite-mapping-coordinate-y" type="number" step="1" value="${selectedCoordinates.y}"></label><label class="sprite-mapping-size-control">Width <input id="sprite-mapping-coordinate-width" data-testid="sprite-mapping-coordinate-width" type="range" min="1" max="${Math.min(200, state.actualWidth)}" value="${Math.min(selectedCoordinates.width ?? selected.width, 200)}"></label><label class="sprite-mapping-size-control">Height <input id="sprite-mapping-coordinate-height" data-testid="sprite-mapping-coordinate-height" type="range" min="1" max="${Math.min(200, state.actualHeight)}" value="${Math.min(selectedCoordinates.height ?? selected.height, 200)}"></label>${renderButton({ children: "Apply entry coordinates", id: "sprite-mapping-apply-entry", testId: "sprite-mapping-apply-entry" })}<span data-testid="sprite-mapping-crop-size">(${selectedCoordinates.x}, ${selectedCoordinates.y}) ${selectedCoordinates.width}×${selectedCoordinates.height}</span></section>` : "";
  const gallery = (state.document?.entries ?? []).map((entry) => { const changed = Boolean(state.changes.entryOverrides[entry.entryId]); return renderButton({ children: `<canvas class="sprite-mapping-preview" width="72" height="72" data-sprite-preview-id="${entry.entryId}" aria-label="${entry.displayName} preview"></canvas><span><strong>${entry.displayName}</strong><small data-testid="sprite-mapping-entry-state">${renderStateMetadata(entry.state, entry.direction)} • ${entry.width}×${entry.height}</small>${changed ? "<small data-testid=\"sprite-mapping-entry-edited\">Edited</small>" : ""}${invalid.has(entry.entryId) ? "<small data-testid=\"sprite-mapping-entry-invalid\">Invalid crop</small>" : ""}</span>`, className: `sprite-mapping-entry ${invalid.has(entry.entryId) ? "is-invalid" : ""}`, testId: "sprite-mapping-entry", selected: entry.entryId === selected?.entryId, pressed: entry.entryId === selected?.entryId, data: { "entry-id": entry.entryId } }); }).join("");
  return `<div class="overlay-box sprite-mapping-panel" data-testid="sprite-mapping-panel"><strong>Sprite Mapping Tool</strong>${renderVisualTemplateSelector(activeTemplateId, "sprite-mapping-template-selector")}<p data-testid="sprite-mapping-message">${state.message}</p>
    ${state.document ? `<p data-testid="atlas-dimensions">Map: ${state.document.declaredWidth}×${state.document.declaredHeight} • Image: ${state.actualWidth}×${state.actualHeight}</p>` : ""}
    ${state.issues.filter((issue) => !issue.entryId).map((issue) => `<p class="mapping-warning" data-testid="atlas-warning">${issue.message}</p>`).join("")}
    ${viewControls}
    <p data-testid="alignment-offset">Bulk alignment for unedited entries: ${state.changes.bulkOffset.x}, ${state.changes.bulkOffset.y}</p>
    ${actions}
    ${selectedPanel}
    <div class="sprite-mapping-gallery" data-testid="sprite-mapping-gallery">${gallery}</div></div>`;
}
