import { resolveEntryCoordinates } from "../../developer/sprite-mapping/atlasMapping";
import type { SpriteMappingState } from "../../developer/sprite-mapping/spriteMappingState";
import { renderVisualTemplateSelector } from "../visualTemplateSelector";

function renderStateMetadata(state: string | null, direction: string | null): string {
  return `State: ${state ?? "default"} • Direction: ${direction ?? "none"}`;
}

export function renderSpriteMappingPanel(state: SpriteMappingState, activeTemplateId = "default-template"): string {
  const selected = state.document?.entries.find((entry) => entry.entryId === state.selectedEntryId) ?? state.document?.entries[0] ?? null;
  const selectedCoordinates = selected && state.document ? resolveEntryCoordinates(selected, state.changes) : null;
  const invalid = new Set(state.issues.filter((issue) => issue.entryId).map((issue) => issue.entryId));
  const dirty = Object.keys(state.changes.entryOverrides).length > 0 || state.changes.bulkOffset.x !== 0 || state.changes.bulkOffset.y !== 0;
  const canSave = Boolean(state.document) && dirty && invalid.size === 0 && !state.isSaving;
  return `<div class="overlay-box sprite-mapping-panel" data-testid="sprite-mapping-panel"><strong>Sprite Mapping Tool</strong>${renderVisualTemplateSelector(activeTemplateId, "sprite-mapping-template-selector")}<p data-testid="sprite-mapping-message">${state.message}</p>
    ${state.document ? `<p data-testid="atlas-dimensions">Map: ${state.document.declaredWidth}×${state.document.declaredHeight} • Image: ${state.actualWidth}×${state.actualHeight}</p>` : ""}
    ${state.issues.filter((issue) => !issue.entryId).map((issue) => `<p class="mapping-warning" data-testid="atlas-warning">${issue.message}</p>`).join("")}
    <div class="sprite-mapping-view-controls"><button id="sprite-mapping-zoom-out" data-testid="sprite-mapping-zoom-out" ${state.zoom <= .5 ? "disabled" : ""}>−</button><output data-testid="sprite-mapping-zoom-value">${Math.round(state.zoom * 100)}%</output><button id="sprite-mapping-zoom-in" data-testid="sprite-mapping-zoom-in" ${state.zoom >= 4 ? "disabled" : ""}>+</button><button id="sprite-mapping-reset-view" data-testid="sprite-mapping-reset-view" ${state.zoom === 1 && !state.viewPan.x && !state.viewPan.y ? "disabled" : ""}>Reset view</button></div>
    <p data-testid="alignment-offset">Bulk alignment for unedited entries: ${state.changes.bulkOffset.x}, ${state.changes.bulkOffset.y}</p>
    <button id="sprite-mapping-reset" data-testid="sprite-mapping-reset" ${!dirty ? "disabled" : ""}>Discard changes</button><button id="sprite-mapping-save" data-testid="sprite-mapping-save" ${canSave ? "" : "disabled"}>${state.isSaving ? "Saving…" : "Save coordinates"}</button><button id="sprite-mapping-copy" data-testid="sprite-mapping-copy" ${state.document ? "" : "disabled"}>Copy mapping JSON</button><button id="sprite-mapping-download" data-testid="sprite-mapping-download" ${state.document ? "" : "disabled"}>Download mapping JSON</button><button id="sprite-mapping-return" data-testid="sprite-mapping-return">Return to Menu</button>
    ${selected && selectedCoordinates ? `<section data-testid="sprite-mapping-selected"><strong>${selected.displayName}</strong><span>${selected.subjectKind} • ${renderStateMetadata(selected.state, selected.direction)}</span><label>X <input id="sprite-mapping-coordinate-x" data-testid="sprite-mapping-coordinate-x" type="number" step="1" value="${selectedCoordinates.x}"></label><label>Y <input id="sprite-mapping-coordinate-y" data-testid="sprite-mapping-coordinate-y" type="number" step="1" value="${selectedCoordinates.y}"></label><label class="sprite-mapping-size-control">Width <input id="sprite-mapping-coordinate-width" data-testid="sprite-mapping-coordinate-width" type="range" min="1" max="${Math.min(200, state.actualWidth)}" value="${Math.min(selectedCoordinates.width ?? selected.width, 200)}"></label><label class="sprite-mapping-size-control">Height <input id="sprite-mapping-coordinate-height" data-testid="sprite-mapping-coordinate-height" type="range" min="1" max="${Math.min(200, state.actualHeight)}" value="${Math.min(selectedCoordinates.height ?? selected.height, 200)}"></label><button id="sprite-mapping-apply-entry" data-testid="sprite-mapping-apply-entry">Apply entry coordinates</button><span data-testid="sprite-mapping-crop-size">(${selectedCoordinates.x}, ${selectedCoordinates.y}) ${selectedCoordinates.width}×${selectedCoordinates.height}</span></section>` : ""}
    <div class="sprite-mapping-gallery" data-testid="sprite-mapping-gallery">${(state.document?.entries ?? []).map((entry) => { const changed = Boolean(state.changes.entryOverrides[entry.entryId]); return `<button class="sprite-mapping-entry ${entry.entryId === selected?.entryId ? "is-selected" : ""} ${invalid.has(entry.entryId) ? "is-invalid" : ""}" data-entry-id="${entry.entryId}" data-testid="sprite-mapping-entry"><canvas class="sprite-mapping-preview" width="72" height="72" data-sprite-preview-id="${entry.entryId}" aria-label="${entry.displayName} preview"></canvas><span><strong>${entry.displayName}</strong><small data-testid="sprite-mapping-entry-state">${renderStateMetadata(entry.state, entry.direction)} • ${entry.width}×${entry.height}</small>${changed ? "<small data-testid=\"sprite-mapping-entry-edited\">Edited</small>" : ""}${invalid.has(entry.entryId) ? "<small data-testid=\"sprite-mapping-entry-invalid\">Invalid crop</small>" : ""}</span></button>`; }).join("")}</div></div>`;
}
