import type { GameStore } from "../state/gameState";
import { returnToMainMenu } from "../state/gameState";
import { loadAtlas, saveAtlas, type LoadedAtlas } from "../../developer/sprite-mapping/atlasMappingClient";
import { createSpriteMappingState } from "../../developer/sprite-mapping/spriteMappingState";
import { emptyChangeSet, resolveAtlasEntries, resolveEntryCoordinates, serializeMappingJson, validateAtlas } from "../../developer/sprite-mapping/atlasMapping";
import { renderSpriteMappingPanel } from "../../ui/overlays/spriteMappingPanel";
import { renderSpriteMappingScene } from "../../render/canvas/renderSpriteMappingScene";
let editor = createSpriteMappingState(); let loaded: LoadedAtlas | null = null; let panStart: { x: number; y: number; panX: number; panY: number } | null = null;
function refresh(): void { if (editor.document) editor.issues = validateAtlas(editor.document, editor.actualWidth, editor.actualHeight, editor.changes); }
const isDirty = () => Object.keys(editor.changes.entryOverrides).length > 0 || editor.changes.bulkOffset.x !== 0 || editor.changes.bulkOffset.y !== 0;
export function openSpriteMapping(store: GameStore): void { editor = createSpriteMappingState(); void loadAtlas().then((atlas) => { loaded = atlas; editor.document = atlas.document; editor.actualWidth = atlas.image.naturalWidth; editor.actualHeight = atlas.image.naturalHeight; editor.selectedEntryId = atlas.document.entries[0]?.entryId ?? null; editor.message = `Loaded ${atlas.document.entries.length} sprite mappings.`; refresh(); store.update(() => {}); }).catch((error: unknown) => { editor.message = error instanceof Error ? error.message : "Unable to load atlas."; store.update(() => {}); }); }
export function renderSpriteMapping(store: GameStore, container: HTMLElement, canvas: HTMLCanvasElement, context: CanvasRenderingContext2D): void {
  const scrollTop = container.querySelector<HTMLElement>(".sprite-mapping-panel")?.scrollTop ?? container.scrollTop;
  refresh(); renderSpriteMappingScene(context, editor, loaded?.image ?? null); container.innerHTML = renderSpriteMappingPanel(editor); const panel = container.querySelector<HTMLElement>(".sprite-mapping-panel"); if (panel) panel.scrollTop = scrollTop; else container.scrollTop = scrollTop; renderGalleryPreviews(container);
  container.querySelectorAll<HTMLButtonElement>("[data-entry-id]").forEach((button) => button.onclick = () => store.update(() => { editor.selectedEntryId = button.dataset.entryId ?? null; }));
  const apply = container.querySelector<HTMLButtonElement>("#sprite-mapping-apply-entry"); apply?.addEventListener("click", () => store.update(() => { const x = Number(container.querySelector<HTMLInputElement>("#sprite-mapping-coordinate-x")?.value); const y = Number(container.querySelector<HTMLInputElement>("#sprite-mapping-coordinate-y")?.value); const width = Number(container.querySelector<HTMLInputElement>("#sprite-mapping-coordinate-width")?.value); const height = Number(container.querySelector<HTMLInputElement>("#sprite-mapping-coordinate-height")?.value); if (!editor.selectedEntryId || ![x, y, width, height].every(Number.isInteger) || width < 1 || height < 1) { editor.message = "Crop values must be whole numbers and dimensions at least one pixel."; return; } editor.changes.entryOverrides[editor.selectedEntryId] = { x, y, width, height }; editor.message = "Entry crop updated."; }));
  const updateSelectedDimension = (field: "width" | "height", value: number) => { const selected = editor.document?.entries.find((entry) => entry.entryId === editor.selectedEntryId); if (!selected || !Number.isInteger(value) || value < 1) return; const current = resolveEntryCoordinates(selected, editor.changes); editor.changes.entryOverrides[selected.entryId] = { x: current.x, y: current.y, width: field === "width" ? value : current.width, height: field === "height" ? value : current.height }; editor.message = "Crop size updated."; refreshLive(container, context); };
  container.querySelector<HTMLInputElement>("#sprite-mapping-coordinate-width")?.addEventListener("input", (event) => updateSelectedDimension("width", Number((event.currentTarget as HTMLInputElement).value)));
  container.querySelector<HTMLInputElement>("#sprite-mapping-coordinate-height")?.addEventListener("input", (event) => updateSelectedDimension("height", Number((event.currentTarget as HTMLInputElement).value)));
  container.querySelector<HTMLButtonElement>("#sprite-mapping-reset")?.addEventListener("click", () => store.update(() => { editor.changes = emptyChangeSet(); editor.message = "Mapping changes discarded."; }));
  container.querySelector<HTMLButtonElement>("#sprite-mapping-reset-view")?.addEventListener("click", () => store.update(() => { editor.zoom = 1; editor.viewPan = { x: 0, y: 0 }; }));
  container.querySelector<HTMLButtonElement>("#sprite-mapping-zoom-in")?.addEventListener("click", () => store.update(() => { editor.zoom = Math.min(4, editor.zoom * 1.5); }));
  container.querySelector<HTMLButtonElement>("#sprite-mapping-zoom-out")?.addEventListener("click", () => store.update(() => { editor.zoom = Math.max(.5, editor.zoom / 1.5); }));
  container.querySelector<HTMLButtonElement>("#sprite-mapping-return")?.addEventListener("click", () => store.update((state) => { if (isDirty() && !window.confirm("Discard unsaved mapping changes?")) return; returnToMainMenu(state); }));
  container.querySelector<HTMLButtonElement>("#sprite-mapping-save")?.addEventListener("click", () => void (async () => { editor.isSaving = true; store.update(() => {}); try { await saveAtlas(editor.changes); await openAndRefresh(); editor.message = "Coordinates saved and reloaded."; } catch (error) { editor.message = error instanceof Error ? error.message : "Save failed."; } finally { editor.isSaving = false; store.update(() => {}); } })());
  container.querySelector<HTMLButtonElement>("#sprite-mapping-copy")?.addEventListener("click", () => void (async () => { if (!editor.document) return; try { await navigator.clipboard.writeText(serializeMappingJson(editor.document, editor.changes)); editor.message = "Resolved mapping JSON copied to clipboard."; store.update(() => {}); } catch { editor.message = "Clipboard access was unavailable."; store.update(() => {}); } })());
  container.querySelector<HTMLButtonElement>("#sprite-mapping-download")?.addEventListener("click", () => { if (!editor.document) return; try { const url = URL.createObjectURL(new Blob([serializeMappingJson(editor.document, editor.changes)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "sprite-mapping.json"; document.body.append(link); link.click(); link.remove(); URL.revokeObjectURL(url); editor.message = "Resolved mapping JSON downloaded."; } catch { editor.message = "Unable to start JSON download."; } store.update(() => {}); });
  canvas.onpointerdown = (event) => { panStart = { x: event.clientX, y: event.clientY, panX: 0, panY: 0 }; canvas.setPointerCapture(event.pointerId); };
  canvas.onpointermove = (event) => { if (!panStart || !editor.document || !editor.selectedEntryId || !loaded) return; const selected = editor.document.entries.find((entry) => entry.entryId === editor.selectedEntryId); if (!selected) return; const base = Math.min((canvas.width - 40) / loaded.image.naturalWidth, (canvas.height - 40) / loaded.image.naturalHeight); const current = resolveEntryCoordinates(selected, editor.changes); editor.changes.entryOverrides[selected.entryId] = { x: Math.round(current.x - (event.clientX - panStart.x) / (base * editor.zoom)), y: Math.round(current.y - (event.clientY - panStart.y) / (base * editor.zoom)), width: current.width, height: current.height }; panStart = { ...panStart, x: event.clientX, y: event.clientY }; refreshLive(container, context); }; canvas.onpointerup = () => { panStart = null; };
}
async function openAndRefresh(): Promise<void> { const atlas = await loadAtlas(); loaded = atlas; editor.document = atlas.document; editor.actualWidth = atlas.image.naturalWidth; editor.actualHeight = atlas.image.naturalHeight; editor.changes = emptyChangeSet(); refresh(); }
function renderGalleryPreviews(container: HTMLElement): void { if (!editor.document || !loaded) return; for (const preview of container.querySelectorAll<HTMLCanvasElement>("[data-sprite-preview-id]")) { const entry = resolveAtlasEntries(editor.document, editor.changes).find((candidate) => candidate.entryId === preview.dataset.spritePreviewId); const context = preview.getContext("2d"); if (!entry || !context) continue; context.clearRect(0, 0, preview.width, preview.height); if (entry.x < 0 || entry.y < 0 || entry.x + entry.width > loaded.image.naturalWidth || entry.y + entry.height > loaded.image.naturalHeight) { context.fillStyle = "#8a1f11"; context.fillRect(0, 0, preview.width, preview.height); continue; } context.drawImage(loaded.image, entry.x, entry.y, entry.width, entry.height, 0, 0, preview.width, preview.height); } }
function refreshLive(container: HTMLElement, context: CanvasRenderingContext2D): void { refresh(); renderSpriteMappingScene(context, editor, loaded?.image ?? null); renderGalleryPreviews(container); const selected = editor.document?.entries.find((entry) => entry.entryId === editor.selectedEntryId); if (!selected) return; const crop = resolveEntryCoordinates(selected, editor.changes); const x = container.querySelector<HTMLInputElement>("#sprite-mapping-coordinate-x"); const y = container.querySelector<HTMLInputElement>("#sprite-mapping-coordinate-y"); if (x) x.value = String(crop.x); if (y) y.value = String(crop.y); const size = container.querySelector<HTMLElement>("[data-testid='sprite-mapping-crop-size']"); if (size) size.textContent = `(${crop.x}, ${crop.y}) ${crop.width}×${crop.height}`; }
